# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 00:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinyURL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitsDatePoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True, db_index=True)),
                ('hits', models.IntegerField(default=0)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tinyURL.Link')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='hitsdatepoint',
            unique_together=set([('day', 'link')]),
        ),
    ]
